# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d6514e01abd45ab0c6c0d1582f2d4547b27136a15cbc8b3c81a01714ab4fd4384e3c50bb55f58c7514d708601ae896781aa22de91f2b65897653897baf9e007

test:
  secret_key_base: dc2157ef6cf772f843205e0e86469327134eeb8b520d19e50a77f9b9a3a985ef35b5b4ecec1fc5d87ab1fc26236c85dc2b80df13f70fd6af01ee26c9f4d43d23

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
